# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aef9c42e7ddfa06fae32a2144c57b085bbe831daa5df57e72b97b27fe67e156e21d3998cfa7fb59e407165b286efc4959e840f68116bb73eace1ce287b91bb59

test:
  secret_key_base: 1ecda8bd2500fbd6c57e9e3fba8d4ccde2df3d833755245956776a7ab5837c24fd3178e739c8e341127955e32f25aeceefd70015631533338a9ba377990d63d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
